version: 0.1.0-{build}

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

environment:
  PATH: C:\Python39-x64;$(PATH)

before_build:
  - cmd: tools\build-googletest.bat 93748a946684defd1494d5585dbc912e451e83f8

build_script:
  - cmd: waf configure -v
  - cmd: waf build_bin -v

test_script:
  - cmd: waf build_test -v
