# SPDX-License-Identifier: MIT

import gtest

from waflib import Utils


def build(bld):
    if Utils.unversioned_sys_platform() == "win32":
        if bld.env.CXX_NAME.lower() == "msvc":
            bld.env.append_unique("CFLAGS", ["/EHa"] + bld.env.CFLAGS_TESTBUILD)
            bld.env.append_unique("CXXFLAGS", ["/EHa"] + bld.env.CXXFLAGS_TESTBUILD)
    elif Utils.unversioned_sys_platform() == "linux":
        pass
    bld.recurse(["gtest-test", "gmock-test"])
    bld.add_post_fun(gtest.summary)
