# SPDX-License-Identifier: MIT


def build(bld):
    bld(
        features="c cxx cxxprogram test",
        source="../../src/super.c testrunner.cpp",
        use=bld.env.GTEST_LIB_NAME,
        includes="../../src/include",
        ldflags=bld.env.LDFLAGS_TESTBUILD,
        target="testrunner",
    )
