# SPDX-License-Identifier: MIT


def build(bld):
    bld(features="c", includes="include", source="main.c", target="main")
    bld(features="c", includes="include", source="add.c", target="add")
    bld(features="c", includes="include", source="dummy.c", target="dummy")
    bld(
        features="c cprogram",
        includes="include",
        use="main add dummy",
        target=bld.env.APPNAME,
    )
