name: Windows Build

on:
  push:
    paths-ignore:
      - docs/**
      - .github/workflows/black.yml
      - .github/workflows/pylint.yml

env:
  WAF_OPTS: -v -c yes

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - buildSystem: cmake
            buildConfiguration: Debug
            googletestVersion: 93748a946684defd1494d5585dbc912e451e83f8
          - buildSystem: cmake
            buildConfiguration: Debug
            googletestVersion: 18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6
          - buildSystem: cmake
            buildConfiguration: Release
            googletestVersion: 93748a946684defd1494d5585dbc912e451e83f8
          - buildSystem: cmake
            buildConfiguration: Release
            googletestVersion: 18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6
          - buildSystem: bazel
            buildConfiguration: Release # configuration is ignored for bazel builds
            googletestVersion: 93748a946684defd1494d5585dbc912e451e83f8
          - buildSystem: bazel
            buildConfiguration: Release # configuration is ignored for bazel builds
            googletestVersion: 18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install Bazel and Ninja
        if: matrix.buildSystem == 'bazel'
        run: |
          choco install bazel --version 3.7.1 --no-progress
          choco install ninja --version 1.10.2 --no-progress
      - name: Add msbuild to PATH
        if: matrix.buildSystem != 'bazel'
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Project configuration
        run: .\waf.bat configure --googletest-build --googletest-version ${{ matrix.googletestVersion }} --googletest-build-tool ${{ matrix.buildSystem }} --googletest-build-config ${{ matrix.buildConfiguration }} ${{ env.WAF_OPTS }}
      - name: Project build
        run: .\waf.bat build_bin ${{ env.WAF_OPTS }}
      - name: Project test
        run: .\waf.bat build_test ${{ env.WAF_OPTS }}
      - name: Project waf *
        run: |
          .\waf.bat clean_bin ${{ env.WAF_OPTS }}
          .\waf.bat clean_test ${{ env.WAF_OPTS }}
          .\waf.bat distclean ${{ env.WAF_OPTS }}
          .\waf.bat dist ${{ env.WAF_OPTS }}
