name: Windows Build

on: push

env:
  WAF_OPTS: -v -c yes

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - buildSystem: cmake
            buildConfiguration: Debug
            googletestVersion: 93748a946684defd1494d5585dbc912e451e83f8
          - buildSystem: cmake
            buildConfiguration: Debug
            googletestVersion: 18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6
          - buildSystem: cmake
            buildConfiguration: Release
            googletestVersion: 93748a946684defd1494d5585dbc912e451e83f8
          - buildSystem: cmake
            buildConfiguration: Release
            googletestVersion: 18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6
          - buildSystem: bazel
            buildConfiguration: Release # configuration is ignored for bazel builds
            googletestVersion: 93748a946684defd1494d5585dbc912e451e83f8
          - buildSystem: bazel
            buildConfiguration: Release # configuration is ignored for bazel builds
            googletestVersion: 18f8200e3079b0e54fa00cb7ac55d4c39dcf6da6
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM
        run: choco install llvm --no-progress
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ matrix.buildSystem }}-${{ matrix.buildConfiguration }}-${{ matrix.googletestVersion }}
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - uses: seanmiddleditch/gha-setup-ninja@v3
        if: matrix.buildSystem == 'bazel'
        with:
          version: 1.10.2
      - uses: abhinavsingh/setup-bazel@v3
        if: matrix.buildSystem == 'bazel'
        with:
          version: 3.7.1
      - name: Add msbuild to PATH
        if: matrix.buildSystem != 'bazel'
        uses: microsoft/setup-msbuild@v1.0.2
      - name: "Restore googletest"
        uses: actions/cache@v2
        with:
          path: ~/googletest
          key: ${{ runner.os }}-googletest-${{ matrix.buildSystem }}-${{ matrix.buildConfiguration }}-${{ matrix.googletestVersion }}
      - name: Project configuration
        run: |
          $env:Path="$env:Path;C:\Program Files\LLVM\bin;"
          .\waf.bat configure --googletest-bootstrap --googletest-version ${{ matrix.googletestVersion }} --googletest-build-tool ${{ matrix.buildSystem }} --googletest-build-config ${{ matrix.buildConfiguration }} ${{ env.WAF_OPTS }}
      - name: Project build
        run: .\waf.bat build_bin ${{ env.WAF_OPTS }}
      - name: Project test
        run: .\waf.bat build_test ${{ env.WAF_OPTS }}
      - name: Run clang-format
        run: .\waf.bat clang-format --cf-arg --Werror --cf-arg --dry-run ${{ env.WAF_OPTS }}
      - name: Project waf *
        run: |
          .\waf.bat clean_bin ${{ env.WAF_OPTS }}
          .\waf.bat clean_test ${{ env.WAF_OPTS }}
          .\waf.bat distclean ${{ env.WAF_OPTS }}
          .\waf.bat dist ${{ env.WAF_OPTS }}
